
version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      # TODO: Remember to update this for each project
      - /Users/sib/apps/boilerplate/db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

